from resources.lib.base.l3.language import _

CONST_BASE_DOMAIN = ''
CONST_BASE_DOMAIN_MOD = False
CONST_BASE_IP = ''
CONST_BASE_URL = ''
CONST_BASE_HEADERS = {}
CONST_CONTINUE_WATCH = False
CONST_DEFAULT_API = ''
CONST_FIRST_BOOT = False
CONST_HAS_LIVE = False
CONST_HAS_REPLAY = False
CONST_HAS_SEARCH = False
CONST_IMAGE_URL = ''
CONST_MOD_CACHE = {}
CONST_ONLINE_SEARCH = False
CONST_START_FROM_BEGINNING = False
CONST_USE_PROXY = False
CONST_USE_PROFILES = False
CONST_VOD_CAPABILITY = []
CONST_WATCHLIST = False